### ISSUE TITLE
[Highlight Search Results in the Browser] Search by flags highlights the enum (1-4) in the browser fields

### ISSUE THREAD

**Issue by kanjieater** [glutanimate/anki-addons-misc#104]
## Which add-on is affected?
Highlight Search Results in the Browser
## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [ x ] In case of a bug: Have you tried restarting Anki?
- [ x ] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [ x ] Did you check the add-on description on AnkiWeb for known issues?
- [ x ] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
When doing a search that contains flags, you use numbers (flag:4 would search all your blue flags). The number of the flag is highlighted in the browser. When the flag:[0-9] params are used, it should not highlight the number of the flag.
[ Please be as specific as possible. Provide screenshots if you think they can help. ]

## How can we reproduce the problem?
Flag something blue. Search for `flag:4`. You will find your blue card. If you have a field with a value of 4 in it, it will be highlighted.

[ What were you doing when the problem occurred? ]
![image](https://user-images.githubusercontent.com/32607317/62590223-3c1fda80-b891-11e9-8b6a-5b1dce853636.png)

**Expected behavior:** [ What you expected to happen ]
No highlighting should happen for flags, since it is an enum representation, and not a contentful search.
**Actual behavior:** [ What actually happened ]
The enum digit is highlighted in content.
**Reproducible?:** [ Can you reliably reproduce the issue by following the steps above? ]
yes.

## Version information

**Anki**

[ Please head to *Help* → *About Anki* and Paste the version string here, e.g.: ]

[ Version 2.0.14 ]
[ Qt 5.12.1 PyQt 5.11.3 ]

**System**

- Operating system: [ Windows]
- Version: [ 10]

**Comment by glutanimate** [comment]
Thanks for the detailed report! Unfortunately there is no way for me to address this, as Qt's native search feature does not allow for adding any type of exclusions to the content that's searched through. However, I will keep monitoring the qt docs and attempt to fix this as soon as it's technically feasible.
