### ISSUE TITLE
[Tag Entry Enhancements] Listing all tags

### ISSUE THREAD

**Issue by tahir-hassan** [glutanimate/anki-addons-misc#11]
This is about tag entry enhancements.

I wish I could list all tags.  For example, lets say I have the following tags in my collection:

* programming
* csharp
* xml

I add the "programming" tag and I get a space at the end.  I then have to remember the letter that the next tag starts with, rather than listing them all.  

I don't have to remember the available tags to select them.  I would want to be able to trigger the listing of ALL tags while there is "programming " in the textbox, without typing in the first letter.  Is that possible?

I will have a go, but I have hardly touched python.

**Comment by glutanimate** [comment]
I'm sorry but which add-on is this in reference to?

Am 17.08.2017 11:20 schrieb "Tahir Hassan" <notifications@github.com>:

**Comment by tahir-hassan** [comment]
Sorry, it is about Tag Entry Enhancements

**Comment by glutanimate** [comment]
Ah, I see what you mean. That would definitely be a useful addition. I'm quite swamped with other project right now, so I probably won't be able to work on this anytime soon, but I'd be more than happy to accept a PR if you decide to implement this yourself.

**Comment by glutanimate** [comment]
Hey Tahir,

[I implemented a variation of this into Anki itself](https://github.com/dae/anki/commit/e2373248731f3346f61cf18d2ef861a9c8929679). You can give it a try by installing the latest Anki 2.1 beta. Since this is now part of Anki I don't think there's any need to add it to the add-on anymore, so I'm closing this for now.

**Comment by tahir-hassan** [comment]
How do you list all tags?  If there a shortcut to do this?

Thanks for your fine work and response.

Tahir

**Comment by glutanimate** [comment]
You mean in the Anki 2.1 beta? You simply type an additional space after entering a tag. Two spaces in a row will trigger the tag completion list to show up with all available tags.

**Comment by tahir-hassan** [comment]
I quite like that behaviour.  Looking forward to trying it.

Can I do anything for you? In terms of testing/documenting?

Best,
Tahir

On 6 Sep 2017 20:10, "Aristotelis" <notifications@github.com> wrote:

You mean in the Anki 2.1 beta? You simply type an additional space after
entering a tag. Two spaces in a row will trigger the tag completion list to
show up with all available tags.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/glutanimate/anki-addons-misc/issues/11#issuecomment-327584401>,
or mute the thread

**Comment by glutanimate** [comment]
That's nice of you to offer, thank. I can't think of anything right now, personally, but I'm sure Damien would [appreciate the help in testing Anki 2.1](https://anki.tenderapp.com/discussions/beta-testing/713-anki-210-beta-13). He's always on the lookout for new beta testers and I think you'd make a great one.
