### ISSUE TITLE
Anki Periodic Table Incorporation

### ISSUE THREAD

**Issue by spartandrew18** [glutanimate/anki-addons-misc#139]
Hi Aristotelis,

I was wondering if you could possibly create a button in Anki that would load up a periodic table. I am kind of shocked an addon like this has not been created yet. I think it would be extremely helpful to premedical students in studying for the MCAT with their Anki decks.

The button could be next to the more options button (bottom right side) when reviewing a deck.

![image](https://user-images.githubusercontent.com/66539077/84078254-9a808280-a9a6-11ea-9b10-ec2580b3b072.png)

Please let me know if this would be possible!

Best,
Andrew

**Comment by glutanimate** [comment]
Hi Andrew,

That's a really cool idea, but unfortunately I have a few too many add-ons on my hand at the moment. I think it could be worth reaching out to the community, though, to see if any other devs would like to pick this up. Some ways you can get in touch with other devs are:

- the [Anki forums](https://www.reddit.com/r/Anki/)
- the [Anki subreddit](https://www.reddit.com/r/Anki/)
- the [Anki discord](https://discord.gg/qjzcRTx)

Hope that helps for now!
