### ISSUE TITLE
[Sync Cursor Between Fields and HTML Editor] Mismatching with Ankidroid

### ISSUE THREAD

**Issue by waldens** [glutanimate/anki-addons-misc#17]
This add-on has a side effect: after the synchronization to the ankidroid, the new line introduced will be interpreted by ankidroid as `<br>`, so once we edit and save cards on ankidroid, every `<br>` will be added to our card and become a truly visible new line (not only in HTML code), which may not be what we want. 

Hope @Glutanimate will find a way to solve this problem. Anki Windows Version 2.0.47 & Ankidroid v2.8.2

Cheers

**Comment by glutanimate** [comment]
Thanks for letting me know. I'll see what I can do.

**Comment by glutanimate** [comment]
I made the newline introduction optional and disabled it by default, at least for as long as AnkiDroid handles HTML whitespace in this way. Thanks again for the report. I will be pushing a new version to AnkiWeb soon.

**Comment by waldens** [comment]
@glutanimate  Is there an easy way, that
just introduce new lines in visual level, not the store/database level?
or
it introduces new lines when we open the edit html input box, and after closing the box, delete the new lines introduced in the background?

I don't know Qt programming, it's just an idea, because this feature is very useful and it's a pity to have to disable it for ankidroid. Anyway, thanks for making so many and so rich addons.

**Comment by glutanimate** [comment]
It's not a bad idea, but there would be no way to tell newlines we've added apart from ones that already existed beforehand, and so we might end up removing some of the user's own formatting when closing the dialog. It really is a pity, but I don't see another solution for now. Hopefully AnkiDroid will implement a proper field editor soon.
