### ISSUE TITLE
[Field history] Could not find any past notes

### ISSUE THREAD

**Issue by Renderca** [glutanimate/anki-addons-misc#182]
## Which add-on is affected?

Field history

## Prerequisite checklist

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

Doesn't matter what deck I'm in, and even if I just created a new note, when I hit "ctrl+alt+h" I get the error message "Could not find any past notes in current deck.  If you just imported a deck you might have to restart Anki."

The addon is not working for me at all, as I always get this error. Though, the addon did work for me in the past. Wondering if anyone else has encountered this problem?
![image](https://user-images.githubusercontent.com/93021540/138540470-b2bee630-cf33-4ef7-b865-c8723c7742ad.png)

## Version information

**Anki**

Version 2.1.35 (84dcaa86)
Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

**System**

Windows 10

**Comment by aboali1hassona** [comment]
I face the same error message. that gets on my nerves 😡😡😡
===========================================
Anki Version 2.1.48

System  Windows 10

**Comment by HarryLang100** [comment]
Hi Renderca,

I believe there's a fix for your issue. First, open the file _editor_field_history.py_. Do this by first opening the "Add-ons" dialog from the anki main window. Then select the add-on "Field History". Then in the sidebar click the button "view files".

Next, change a line of code [as shown here](https://github.com/glutanimate/anki-addons-misc/commit/186d5bf7b97929aaa16ba64baadcd3b90efe062b).

Does that work?

Best wishes,
Harry

**Comment by Renderca** [comment]
> Hi Renderca,
> 
> I believe there's a fix for your issue. First, open the file _editor_field_history.py_. Do this by first opening the "Add-ons" dialog from the anki main window. Then select the add-on "Field History". Then in the sidebar click the button "view files".
> 
> Next, change a line of code [as shown here](https://github.com/glutanimate/anki-addons-misc/commit/186d5bf7b97929aaa16ba64baadcd3b90efe062b).
> 
> Does that work?
> 
> Best wishes, Harry

Hi Harry,

This worked.  Thanks a ton!
