### ISSUE TITLE
[Search and Replace Tags] Request: Auto-fill the current search-tag

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [glutanimate/anki-addons-misc#19]
If I click a tag in the left hand column, get `tag:tex`, hit ⌘A, and then **Tags → Replace Tag …**, I'd assume the “original tag” would be auto-filled with `tex`.

Is this something you could easily add?

(Heh, I keep finding myself typing the *replacement* name as soon as I hit “replace tag” — over and over; somehow it's permanently burned into my muscle memory, just assuming that it's ‘replacing’ the currently-selected tag!)

**Comment by glutanimate** [comment]
That sounds like a great idea, although handling searches with multiple tags might be a bit tricky. Still, I'll add this to the to-do list and will see if I can get back to it once I find the time.

**Comment by Dougwar** [comment]
Hi I mean one tag that search in multiples websites and open it in tabs. 
I made one in java but I cant get to work with this addon
exemple here;
	<script>

			var jan1;
			var jan2;
			var jan3;
			var jan4;


		function search() {

			var a = document.getElementById("meuinput").value;

			jan1 = window.open('https://characterpop.com/search?q='+a, '_blank');
			jan2 = window.open('http://www.nciku.com/search/all/'+a, '_blank');
			jan3 = window.open('http://www.forvo.com/word/' + a + '/#zh', '_blank');
			jan4 = window.open('http://translate.google.com/translate?hl=en&sl=zh-CN&tl=en&u=http%3A%2F%2Fwww.zdic.net%2Fsousuo%2F%3Fq%3D'+a, '_blank');

for exemplo I search a word in chinese then it open four tabs seaching for this words in this sites. 
Thanks

**Comment by glutanimate** [comment]
Hi Dougwar, I think you meant to comment on [your issue](https://github.com/glutanimate/anki-addons-misc/issues/20)? This is a different one.

**Comment by glutanimate** [comment]
Thanks again for the helpful feedback @ELLIOTTCABLE. I'm closing this issue report as my development focus has switched to [BetterTags](https://www.patreon.com/posts/new-way-to-tags-19770524), which I think addresses this and other usability issues with the original, simpler add-on. While BetterTags is currently paywalled on my Patreon, a public release is on my roadmap.
