### ISSUE TITLE
[Context Menu Search] Multisearch 

### ISSUE THREAD

**Issue by Dougwar** [glutanimate/anki-addons-misc#20]
Hi, thanks for this awesome addon.
Can you add a option to search in multisites in the same time?
thanks

**Comment by glutanimate** [comment]
I can see how this feature might be useful, but I currently don't have the time to implement it. I'll add it to the to-do list, though. If anyone feels like working this in, I'd be more than happy to accept a PR.

**Comment by glutanimate** [comment]
@cjon256 Thanks again for the contribution! Really appreciate it. Closing this for now as the feature is implemented in the master branch. I'll try to update the listing on AnkiWeb soon.
