### ISSUE TITLE
[Progress Bar] Progress goes backwards if cards are rated "again"

### ISSUE THREAD

**Issue by qsniyg** [glutanimate/anki-addons-misc#21]

**Comment by glutanimate** [comment]
Yeah, this is a general issue with the add-on and caused by the total card queue length increasing. Not sure if and how it can addressed. I mean, strictly speaking, your progress does move backward if you have to view a card again, but I do understand how this could be confusing.

**Comment by qsniyg** [comment]
I guess this would involve running a query that finds all due cards, similar to `col.shed.deckDueList()`, except excludes cards that originate from the same note.

I tried looking into this, but I'm not versed enough in SQL to know how.

**Comment by afoalb** [comment]
i've had the same problem! At the first sight I found the add-on great, but now...

**Comment by ChrisK91** [comment]
Would it be an option to track state of the cards in the review pile, an track progress on a "per-card" basis? Because the total number of cards should not change, shouldn't it?

**Comment by glutanimate** [comment]
Hi again,

This should be fixed for the most part with d10e5e300518b14aa03d65ee5ff930a82cb9853c (thanks to @liuzikai !). Progress can still go backwards under some circumstances which are explained [here](https://github.com/glutanimate/anki-addons-misc/blob/master/src/reviewer_progress_bar/reviewer_progress_bar.py#L39-L60), but this behavior can be changed by setting [`forceForward`](https://github.com/glutanimate/anki-addons-misc/blob/master/src/reviewer_progress_bar/reviewer_progress_bar.py#L69) to True. In the AnkiWeb release I will be likely making this the default.

But before that I'd really appreciate you guys' feedback on the new version of the add-on. If you can, please do give it a try by checking the files out [here](https://github.com/glutanimate/anki-addons-misc/tree/master/src/reviewer_progress_bar), and let me know if the issue has been addressed.

**Comment by glutanimate** [comment]
I'm closing this issue report for now due to lack of activity, but please feel free to re-open it at any point if the changes in the latest git build don't help.
