### ISSUE TITLE
[Search and Replace Tags] Support substring replacements, e.g. for hierarchical tags

### ISSUE THREAD

**Issue by TLLee19** [glutanimate/anki-addons-misc#22]
Hi Glutanimate,

Does using "search and replace" working with Hierarchical tags? I tried to replace a "master" tag, but it doesn't work. 

Any help offered would be greatly appreciated

Thank you very much

**Comment by TLLee19** [comment]
Hi Glutanimate, 

I just found that it is not currently possible to search and replace master tags. Would it be possible to commission this feature?

Thank you very much

**Comment by glutanimate** [comment]
Hey TLLee19,

that sounds like a cool feature to have! Sure, just drop me an email at ankiglutanimate [ατ] gmail . com, so that we can discuss the implementation details and everything else.

Best,
Glutanimate

**Comment by PCwizCube** [comment]
Has this issue been addressed? I saw on the Anki website for this add-on, some users had success with changing the hierarchal tags. However I still have the same issue as TLLee19. 

Anki v2.0.47

Thank you

**Comment by glutanimate** [comment]
@TLLee19  and @PCwizCube thanks for the feedback guys. Support for tag substring replacements is now implemented in the BetterTags add-on: https://www.patreon.com/posts/new-way-to-tags-19770524

It's currently paywalled on my Patreon, but a public release is on the roadmap.
