### ISSUE TITLE
[Progress Bar] Make progress persistent across moving between decks

### ISSUE THREAD

**Issue by SebastianGG** [glutanimate/anki-addons-misc#25]
First of all, thanks for your great add-ons and video tutorials.

I use your progress bar add-on, and I wonder if it would be possible to make the progress bar persistent. As it currently works, if I open a deck with 50 pending cards, review 10, and close the deck, the next time I open it the progress bar will be reseted to "0/40 (0%)". It would be most useful if, instead, the progress bar continued where I left, at "10/50 (20%)".

**Comment by ghost** [comment]
Also experiencing this. If persistent it would be perfect.

**Comment by glutanimate** [comment]
Added with d10e5e300518b14aa03d65ee5ff930a82cb9853c. All thanks go to @liuzikai !
