### ISSUE TITLE
[Progress Bar] Make it possible to have a progress bar for remaining time

### ISSUE THREAD

**Issue by SebastianGG** [glutanimate/anki-addons-misc#27]
There's a timeboxing setting in Anki, where you can set the duration of each timebox in minutes. It could be useful and motivating to be able to have a progress bar showing the passage of time according to this setting, so that you have a visual reference of how much time you have left until your current timebox ends.

**Comment by glutanimate** [comment]
Coming a bit late, but thanks for the suggestion!

I feel that this is somewhat outside the scope of this add-on, but perhaps it's something that could be implemented in the [Remaining Time add-on](https://ankiweb.net/shared/info/519467573)?
