### ISSUE TITLE
<Search and Replace Tags> May I delete a tag of many notes by replacing them with "null"?

### ISSUE THREAD

**Issue by hehehillman** [glutanimate/anki-addons-misc#29]
I've added some tag to my notes that is not useful, So I tried to delete them by replacing them with "null", But it doesn't work?May I have some suggestion? Thanks!

**Comment by hehehillman** [comment]
I've solve it. just to replace the tag with ""

**Comment by glutanimate** [comment]
Sorry, coming a bit late, but Anki has this built in: You can invoke the tag batch-deletion dialog with CTRL+ALT+T.
