### ISSUE TITLE
[Batch Note Editing] Support regex

### ISSUE THREAD

**Issue by malore** [glutanimate/anki-addons-misc#34]
Regex support will allow to remove/replace only specific strings and add strings anywhere within the fields. In my case, it will delete the need for exporting, editing and reimporting the cards.

**Comment by glutanimate** [comment]
Thanks for your feedback. The add-on is mostly designed as a simplified version of Anki's very own [Find and Replace dialog](https://apps.ankiweb.net/docs/manual.html#find-and-replace), which actually does support RegEx. Perhaps that could work for your use cases?

**Comment by malore** [comment]
Thank you very much. It's what I was looking for. Sorry but I thought Anki didn't have anything similar built in.

**Comment by glutanimate** [comment]
No problem! Anki has a lot of hidden goodies. Glad to hear this works for you.
