### ISSUE TITLE
[Speed Focus Mode] AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by khonkhortisan** [glutanimate/anki-addons-misc#38]
![image](https://user-images.githubusercontent.com/1996449/36345765-099af13e-1429-11e8-9608-58975e62710a.png)

**Comment by khonkhortisan** [comment]
Removing `.decode(sys_encoding)` worksforme

**Comment by glutanimate** [comment]
Anki 2.1, right?

**Comment by glutanimate** [comment]
Just pushed a patch that should fix this. Thanks again for the report!
