### ISSUE TITLE
[Speed Focus Mode] Option to choose rating to be applied

### ISSUE THREAD

**Issue by Phoenix-Brothres** [glutanimate/anki-addons-misc#40]
Please also add this option for your [plugin](https://ankiweb.net/shared/info/1046608507):
Automatically rate as "good" and showing the next card. That's what really makes it all automatic.
Actually giving user the option to choose if the automatic rate would be "good" or "again" after a certain time.
Thanks

**Comment by glutanimate** [comment]
Thanks for the suggestion. This sounds like a cool feature to have, but it would somewhat go against the main idea behind the add-on which is to punish you for being too slow, right?

**Comment by JulyMorning** [comment]
probably, it's something like I've just mentioned here #53.

**Comment by glutanimate** [comment]
Closing this, as explained here: https://github.com/glutanimate/anki-addons-misc/issues/53#issuecomment-400382934
