### ISSUE TITLE
[Speed Focus Mode] Not working

### ISSUE THREAD

**Issue by antarticwind** [glutanimate/anki-addons-misc#41]
## Which add-on is affected?
Speed Focus Mode (auto-alert, auto-reveal, auto-fail) (1046608507) is not working at all, not sure why. I have other add-ons like Progress Bar or the Puppy Reinforcement. Today I tried with speed focus but nothing happen. 
I already tried changing the seconds or changing the deck of my cards

## Prerequisite checklist
- [X] In case of a bug: Have you tried restarting Anki?
- [X] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [X] Did you check the add-on description on AnkiWeb for known issues?
- [X] Did you perform a cursory search through existing issue reports?

## How can we reproduce the problem?
I installed the addon, changed the options of the deck
![image](https://user-images.githubusercontent.com/36802072/36635381-86c3d8ba-1992-11e8-985c-d7d088dee9e6.png)
but when I start studying the deck, nothing happen 

**Expected behavior:** Play an alert, reveal the answer or fail the card
**Actual behavior:** After several minutes waiting with a card, nothing happen
**Reproducible?:** Yes, everytime

## Version information
Version 2.0.32
Qt 4.8.7 PyQt 4.11.4

**System**
- Operating system: Linux
- Version: Ubuntu Mate 16.04.2 LTS

**Comment by glutanimate** [comment]
Hi @antarticwind,

thanks a lot for the detailed report!

It appears that you you're using a very old version of Anki (builds shipped through your distro's packaging system are unfortunately usually very old). Could you please try updating to the [static build available on AnkiWeb](https://apps.ankiweb.net/) (2.0.47) and see if the add-on works then?

**Comment by antarticwind** [comment]
Thank for you reply! :)

Ok, I reinstalled anki and the addon again (Now I have the Version 2.0.47 - Qt 4.8.1 PyQt 4.9.1), but it "kind" of work now :0

It only works now with the "default" option group. And it doesn't matter what I put in the "seconds" for another group options, it always use the seconds in the "default" option group 

For example: I have a deck called "Pathoma", and 3 group option ("Default", "Unlimited Study" and "Relax")
-In "Default" I put 7 seconds for alert, 13 for show answer and 15 for 'again'
-In "Unlimited Study" I put 15 seconds for alert, 21 for show answer and 25 for 'again'
-In "Relax" everything is 0
It doesn't matter which group option I select for pathoma (default, unlimited or relax), it always start the alert at 7

Really thank you for your work, much appreciated :)

**Comment by glutanimate** [comment]
Thanks for giving this another try. Quick question: Are you studying these decks directly, or you studying them from a parent deck? I.e.: Are they all subdecks of another deck?

**Comment by antarticwind** [comment]
Ohhhh, that's it!!! :D 
I didn't know you had to change every subdeck or otherwise all of them remain in "default". 
I imagined that with only changing the parent deck, every subdeck will change afterward

Ok, "problema resuelto", thank you very much!!! ^-^

**Comment by glutanimate** [comment]
No problem :). Anki's deck options system and how it applies between parent and subdecks can be very confusing. Glad to hear that everything is working now!

Enjoy the ad-don and good luck with your studies!
