### ISSUE TITLE
[Batch Note Editing] Disabling and removing buttons for "Add before" "Add after" and limiting actions to a specific field

### ISSUE THREAD

**Issue by AuntMinnie** [glutanimate/anki-addons-misc#45]
## Prerequisite checklist

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x ] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
I am looking to make two edits to the code 1) make "replace" is the only option for edits, and 2) have this only apply to a specified field. Right now my basic cards have three fields: "front", "back", and "notes". I would like to only have the ability to replace the "notes". I am a novice, and tried editing the code myself with no success. Screenshot of the add on box with buttons that I would like to be disabled/removed are circled in red.

<img width="541" alt="messages image 2658430279" src="https://user-images.githubusercontent.com/38514793/38967469-208b163e-4355-11e8-8377-e7f929c21bd2.png">

## How can we reproduce the problem?
N/A

**Expected behavior:**  N/A

**Actual behavior:** N/A

**Reproducible?:** N/A

## Version information

**Anki**

[ Please head to *Help* → *About Anki* and Paste the version string here, e.g.: ]

[ Version 2.0.47 ]
[ Qt 4.8.1 PyQt 4.9.1 ]

**System**

- Operating system: [ Windows/macOS/Linux ]
- Version: [ e.g. 10, High Sierra, Ubuntu 18.04 ]

**Comment by glutanimate** [comment]
Hi @AuntMinnie 

Sorry for the late response. In case you're still interested in doing your edits:

- The buttons are defined in this code segment: https://github.com/glutanimate/anki-addons-misc/blob/master/src/browser_batch_edit/browser_batch_edit.py#L55-L62

- and the contents of the fields drop-down selector are set in this segment: https://github.com/glutanimate/anki-addons-misc/blob/master/src/browser_batch_edit/browser_batch_edit.py#L47-L48
