### ISSUE TITLE
[Speed Focus Mode] Feature request: changing default answer.

### ISSUE THREAD

**Issue by JulyMorning** [glutanimate/anki-addons-misc#53]
It's already made [here](https://github.com/jaksz/anki-blitz) by jaksz. The add-ons are so similar. They should add some value to each other.

To make it work with your addon, I've just imported time at line 21 (`import time`), then added a couple of lines to _clear_again_timeout()_ (the original ones):

```
    global start_time
    start_time = time.time()
```

and then added this function to the body (it's original too, but I made it use your values):

```
def myDefaultEase(self):
    elapsed_time = time.time() - start_time
    if elapsed_time < self.mw.col.decks.confForDid(self.card.odid or self.card.did).get('autoAlert', 0):
        return 3
    if elapsed_time < self.mw.col.decks.confForDid(self.card.odid or self.card.did).get('autoAnswer', 0):
        return 2
    else:
        return 1
```

I found it [here](https://ankiweb.net/shared/info/678078605), it has MIT license. Hasn't updated for ≈ 2 years. Just don't want to make it again, if your addon gets some updates. It seems cool answering cards just by one button.

By the way, obviously, it doesn't use «4» (very easy) button, but it's simple enough to add it (for example, if your answer time is half `autoAlert`:

```
    if elapsed_time < (self.mw.col.decks.confForDid(self.card.odid or self.card.did).get('autoAlert', 0)/2):
        return 4
```

**Comment by glutanimate** [comment]
Huh, I had no idea that add-on existed. I actually wrote a very similar one a few months ago (yet unpublished on AnkiWeb):

https://github.com/glutanimate/anki-addons-misc/blob/master/docs/descriptions.md#reviewer_auto_rate_hotkey-hotkey-that-auto-rates-based-on-elapsed-time

https://github.com/glutanimate/anki-addons-misc/tree/master/src/reviewer_auto_rate_hotkey

I think it makes sense separating this functionality from speed focus mode as it fulfills a different use case (time-based evaluation vs encouraging faster self evaluation). So I'll close this and the other issue for now, as I they are outside the scope of Speed Focus Mode and there is a good alternative with these other add-ons.

Thanks once again for your thoughtful feedback, though!

**Comment by JulyMorning** [comment]
Can you give an advice, what lines should I add to the original addon to use Speed Focus' values? I have a very general understanding, don't know much about anki addons' ecosystem. I just wanted it to work with different timings for decks. Thanks.

**Comment by glutanimate** [comment]
@JulyMorning I'm sorry, but could you please elaborate on what you'd like to achieve? the Auto rate hotkey add-on should allow you to set up deck-specific values. Wouldn't that cover your use case?
