### ISSUE TITLE
[Toggle Full Screen and Hide Menu Bar] does not unhide the menu bar.

### ISSUE THREAD

**Issue by aleksejrs** [glutanimate/anki-addons-misc#6]
For https://ankiweb.net/shared/info/1604562448 on Anki 2.0.43.
(I couldn't find the addon here)

**Comment by glutanimate** [comment]
Thanks for the report, Aleksej. I was experiencing the same issue, so I actually ended up disabling the menu bar hiding in my local copy entirely. I'll see if I can find a proper solution soon.

**Comment by glutanimate** [comment]
@aleksejrs, could you give the [new GitHub version](https://github.com/glutanimate/anki-addons-misc/blob/master/src/main_fullscreen.py) a try? The logic hasn't really changed, but I haven't been able to reproduce this issue thus far (neither on 2.0 nor 2.1). If you do run into this, could you tell me which steps you took exactly?

**Comment by ankitest** [comment]
New GitHub version works perfectly well on 2.0.47 under Windows 7 SP1.  

To reproduce this bug with https://ankiweb.net/shared/info/1604562448 you need to maximize Anki in window mode.

**Comment by glutanimate** [comment]
@ankitest Thanks for chiming in. Just to be clear, you haven't experienced this issue at all with the new version?

**Comment by aleksejrs** [comment]
No problem on 2.0.47 on Debian stable, maximized or windowed.

**Comment by glutanimate** [comment]
Awesome, thanks for letting me know. I will push the new version to AnkiWeb soon.

**Comment by aleksejrs** [comment]
Uh, sorry. When the window was maximized, the menu is just not hidden.

**Comment by ankitest** [comment]
Thanks, @aleksejrs When the window was maximized, the menu bar is just not hidden. @glutanimate  On any Anki 2.0 and Anki 2.1 under Windows 7 also.

What about hotkeys? `Ctrl+Z` to undo last answer still does not work when main menu is hidden.

**Comment by glutanimate** [comment]
Ok, that's what I expected since the logic didn't really change with the refactoring. I will see if anything can be done about this or if it's just a Qt bug.

@ankitest, let's track the hotkey issue here: https://github.com/glutanimate/anki-addons-misc/issues/18

**Comment by glutanimate** [comment]
Please give the latest release a try guys. I can't reproduce the issue on Linux any more.

P.S.: @ankitest, I've also fixed #18 by introducing a Ctrl+Z hotkey. Please let me know if it works for you.

**Comment by glutanimate** [comment]
I've also made the menu bar hiding optional, for users out there that want to preserve all shortcuts (e.g. those assigned by add-ons) [13c36816f2b6b32605948f805f4a59ed6cdead2f].

**Comment by aleksejrs** [comment]
Works well with 2.0.47 and 2.1.0beta15-amd64, including the option.

On 2.1, which is remarkably slow, menu hiding goes through an ugly blink.

**Comment by glutanimate** [comment]
Thanks for letting me know, aleksej. Yeah, 2.1 has been rather slow for me as well. Here's to hoping that some of these problems will get fixed with the new Qt release.

@ankitest, is the add-on working fine on your end as well? If so, I would update the AnkiWeb listing with the new release.

**Comment by ankitest** [comment]
Anki 2.1 under Win7: ^Z does not work under fullscreen mode (original hotkeys are Ctrl+Alt+Z) and F11 works with ugly flashing.

Anki 2.0 under Win7: works perfectly well.
