### ISSUE TITLE
Where to find the "Refresh Media References" source codes?

### ISSUE THREAD

**Issue by bluebad** [glutanimate/anki-addons-misc#73]
## Which add-on is affected?

[ Please mention the add-on in the issue title as follows: "[Add-on name] My issue" ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [ ] In case of a bug: Have you tried restarting Anki?
- [ ] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [ ] Did you check the add-on description on AnkiWeb for known issues?
- [ ] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

[ Please be as specific as possible. Provide screenshots if you think they can help. ]

## How can we reproduce the problem?

[ What were you doing when the problem occurred? ]

1. [ First step ]
2. [ Second step ]
3. [ and so on... ]

**Expected behavior:** [ What you expected to happen ]

**Actual behavior:** [ What actually happened ]

**Reproducible?:** [ Can you reliably reproduce the issue by following the steps above? ]

## Version information

**Anki**

[ Please head to *Help* → *About Anki* and Paste the version string here, e.g.: ]

[ Version 2.0.47 ]
[ Qt 4.8.1 PyQt 4.9.1 ]

**System**

- Operating system: [ Windows/macOS/Linux ]
- Version: [ e.g. 10, High Sierra, Ubuntu 18.04 ]

**Comment by glutanimate** [comment]
Hi @bluebad,

see here: https://github.com/glutanimate/anki-addons-misc/tree/master/src/overview_refresh_media
