### ISSUE TITLE
[Batch Note Editing] Idea request

### ISSUE THREAD

**Issue by Z1839** [glutanimate/anki-addons-misc#76]
This addon is great. I thought it would be neat to have a feature to selectively replace certain edits, rather than simply replacing the entire selected field

**Comment by glutanimate** [comment]
Hey Z! Glad you like the add-on. Selective replacements should be possible with Anki's [Find and Replace](https://apps.ankiweb.net/docs/manual.html#find-and-replace) feature. Batch Note Editing basically just offers a simplified sub-set of Anki's built in tool.

Hope that helps!
