### ISSUE TITLE
puppy reinforcement broken pipe

### ISSUE THREAD

**Issue by mbidwell** [glutanimate/anki-addons-misc#82]
## Which add-on is affected?

[ "[puppy reinforcement] broken pipe" ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

[anki will not start up, broken pipe error, cannot find anki2 folder to fix code. ]

## How can we reproduce the problem?

[ adding custom text to puppy reinforcement? ]

1. [ adding custom text, i believe i forgot a single comma ]
2. [ Second step ]
3. [ and so on... ]

**Expected behavior:** [ add text ]

**Actual behavior:** [ anki would not start ]

**Reproducible?:** [ I believe so, should only need to miss a comma ]

## Version information

**Anki 2.0**

[ Please head to *Help* → *About Anki* and Paste the version string here, e.g.: ]
cannot access currently with my issue
[ Version 2.0.47

 ]
[ Qt 4.8.1 PyQt 4.9.1 ]

**System**

- Operating system: [ mac ]
- Version: [ 10.14.2 ]

<img width="469" alt="Screen Shot 2019-03-26 at 9 59 05 AM" src="https://user-images.githubusercontent.com/48955013/55003780-64c4c900-4faf-11e9-97a6-81f9fd8d9aa8.png">

<img width="412" alt="Screen Shot 2019-03-26 at 9 59 17 AM" src="https://user-images.githubusercontent.com/48955013/55003791-69897d00-4faf-11e9-93d1-ad9e0ad75f37.png">

<img width="411" alt="Screen Shot 2019-03-26 at 9 59 42 AM" src="https://user-images.githubusercontent.com/48955013/55003801-6e4e3100-4faf-11e9-86cf-8b37f1ebcf66.png">

**Comment by mbidwell** [comment]
fixed the problem, did not know about holding the shift button on start up to disable add-ons, was able to uninstall and reinstall the addon with no challenges after fixing the coding

**Comment by glutanimate** [comment]
Thanks for letting me know about this @mbidwell . That broken pipe error might be an Anki bug, but generally Puppy Reinforcement definitely needs to handle cases like this better. I will take this into consideration for the 2.1 port.

**Comment by mbidwell** [comment]
I appreciate you reaching out. If you have any questions about the experience that I had and how I was able to fix it, feel free to reach out. Huge fan of the add-on.

mbidwell
