### ISSUE TITLE
[More addon buttons for new cards] Anki 2.1 - Addon update error

### ISSUE THREAD

**Issue by Z1839** [glutanimate/anki-addons-misc#84]
On Anki 2.1 when I check for updates for addons, i'm getting the error 

"Please check your internet connection.

'<' not supported between instances of 'int' and 'NoneType'"

I disabled the addon and the error disappeared.

Thanks for everything!

**Comment by glutanimate** [comment]
Thanks for the report! Just submitted a pull request to Anki to address this: https://github.com/dae/anki/pull/299
