### ISSUE TITLE
[Night Mode] Buggy sidebar revisited

### ISSUE THREAD

**Issue by gajewsk2** [glutanimate/anki-addons-misc#94]
## Which add-on is affected?

[ Please mention the add-on in the issue title as follows: "[Add-on name] My issue" ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [X] In case of a bug: Have you tried restarting Anki?
- [X] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [X] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

- In the browser, the tag tree sidebar was observed to disappear when resized using Anki on Windows, which may (or may not) be related to changes made by this addon. Selectively disabling styling of the Browser (View -> Choose what to style -> untick "Browser") was reported to solve this problem. 

In regards to this message, i followed these steps, and found it did not fix the problem by selectively disabling the browser. I then disable scroll bars styling as well. Unticking the style dialogs did fix it.

## How can we reproduce the problem?

1. Have everything styled (in dialogs and main window)
2. Make sure the browser has the scroll bar opened by default
3. open browser and resize

**Expected behavior:** Sidebar should take a reasonable amount of width

**Actual behavior:** side bar shows about 3 char width

**Reproducible?:** It's not consistent

## Version information

**Anki**

[ Please head to *Help* → *About Anki* and Paste the version string here, e.g.: ]

[ Version 2.1.15 ]
[ Qt 5.9.2 PyQt 5.9 ]

**System**

- Operating system: [ Windows ]
- Version: [ 10 ]

**Comment by glutanimate** [comment]
Hi Micah,

I think you might have submitted this to the wrong issues tracker? Night Mode's tracker is here: https://github.com/krassowski/Anki-Night-Mode

**Comment by gajewsk2** [comment]
indeed i did.. sorry!
