### ISSUE TITLE
[browser_search_highlight_results] results not highlighted - quoted, trailing space

### ISSUE THREAD

**Issue by ijgnd** [glutanimate/anki-addons-misc#99]
originally reported on [ankiweb on 2019-05-22 by user dashakol](https://anki.tenderapp.com/discussions/add-ons/33925-highlight-search-results-in-the-browser-doesnt-highlight-when-the-last-character-is-a-space-inside-quotes)

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

Anki 2.1.13 with browser_search_highlight_results (downloaded today) and no other add-ons in a new profile:

**when a string is quoted only the last word is highlighted**

![highlight_wo](https://user-images.githubusercontent.com/40218852/58166479-70fc9800-7c79-11e9-8045-4d7959a406b4.png)

&nbsp;

**if there's a trailing slash there's no highlighting:**
![highlight_with](https://user-images.githubusercontent.com/40218852/58166521-870a5880-7c79-11e9-9fad-84ae98b2dfc5.png)

**Reproducible?:** [ Can you reliably reproduce the issue by following the steps above? ]

Yes

## Version information

**Anki**

    Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
    Platform: Windows 10
    Flags: frz=True ao=True sv=1

    Add-ons:

    Highlight Search Results in the Browser

**System**

- Operating system: Win
- Version:  10Pro 1809 64bit

**Comment by glutanimate** [comment]
Thanks for bringing this to my attention and taking the time to compile this excellent bug report. I can confirm this behavior here and will look into a solution.

**Comment by glutanimate** [comment]
Seems like GitHub needs to work on its natural language processing...

In any case, would you mind giving the latest master build a try? I pushed a few changes which should hopefully address the issue (and also improve a few other tidbits here and there).

PS: It can be very time-consuming to sift through the flood of (usually incomplete) support requests across Reddit, Tenderapp, AnkiWeb, emails, etc. So the work you've put towards repackaging this issue report and adding all of the relevant info is highly appreciated. Thank you!

**Comment by ijgnd** [comment]
did a brief test on 2.0 and 2.1 and it seems to work as intended (given the limitations you have listed as todo). That was a really quick fix!

**Comment by glutanimate** [comment]
Great, thanks!
